# Site settings
title: Pingxia@sharing
email: 
description: > # this means to ignore newlines until "baseurl:"
 Here is my personal blog sharing my experiences, thoughts and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pingxiahu.me" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

# Time zone
timezone: Berlin/Germany
